## オープンデータの数値化
長野県自転車盗難データを数値化する。

In [1]:
import pandas as pd
df = pd.read_csv("./CSV/input/nagano_2018zitensyatou.csv", encoding="cp932")
df.head()

,罪名,手口,管轄警察署（発生地）,管轄交番・駐在所（発生地）,市区町村コード（発生地）,都道府県（発生地）,市区町村（発生地）,町丁目（発生地）,発生年月日（始期）,発生時（始期）,発生場所の属性,被害者の年齢,被害者の職業,施錠関係
0,窃盗,自転車盗,中野,中野市信州中野駅前交番,202118,長野県,中野市,大字一本木,2018/7/26,13,駐車（輪）場,10歳代,中学生,施錠した
1,窃盗,自転車盗,中野,中野市信州中野駅前交番,202118,長野県,中野市,大字篠井,2018/9/13,6,駐車（輪）場,10歳代,高校生,施錠した
2,窃盗,自転車盗,中野,中野市信州中野駅前交番,202118,長野県,中野市,大字篠井,2018/10/6,12,駐車（輪）場,10歳代,高校生,施錠した
3,窃盗,自転車盗,中野,中野市信州中野駅前交番,202118,長野県,中野市,大字篠井,2018/12/8,13,駐車（輪）場,10歳代,高校生,施錠した
4,窃盗,自転車盗,中野,中野市信州中野駅前交番,202118,長野県,中野市,西１丁目,2018/6/22,7,駐車（輪）場,10歳代,高校生,施錠した

In [2]:
# 列名変更
df = df.rename(columns={
    '発生年月日（始期）': 'occurDate',
    '発生時（始期）': 'occurTime',
    '被害者の年齢': 'age',
    '被害者の職業': 'occupation',
    '施錠関係': 'isRock',
})
# 列削除
del df['罪名']
del df['手口']
del df['管轄警察署（発生地）']
del df['管轄交番・駐在所（発生地）']
del df['市区町村コード（発生地）']
del df['都道府県（発生地）']
del df['市区町村（発生地）']
del df['町丁目（発生地）']
del df['発生場所の属性']
df.head()

   occurDate occurTime   age occupation isRock
0  2018/7/26        13  10歳代        中学生   施錠した
1  2018/9/13         6  10歳代        高校生   施錠した
2  2018/10/6        12  10歳代        高校生   施錠した
3  2018/12/8        13  10歳代        高校生   施錠した
4  2018/6/22         7  10歳代        高校生   施錠した

In [3]:
# isRock(施錠状態)の数値化
print("カテゴリ値の確認", df["isRock"].unique())
df["isRock"][df["isRock"] == "施錠した"] = 1
df["isRock"][df["isRock"] == "施錠せず"] = 0
# intに型変換
df["isRock"] = df["isRock"].astype(int)
# 数値化を確認
df.head()

カテゴリ値の確認 ['施錠した' '施錠せず']

   occurDate occurTime   age occupation  isRock
0  2018/7/26        13  10歳代        中学生       1
1  2018/9/13         6  10歳代        高校生       1
2  2018/10/6        12  10歳代        高校生       1
3  2018/12/8        13  10歳代        高校生       1
4  2018/6/22         7  10歳代        高校生       1

In [4]:
# occupation(職業)の数値化
print("カテゴリ値の確認", df["occupation"].unique())
df["occupation"][df["occupation"] == "小学生"] = 0
df["occupation"][df["occupation"] == "中学生"] = 1
df["occupation"][df["occupation"] == "高校生"] = 2
df["occupation"][df["occupation"] == "大学生"] = 3
df["occupation"][df["occupation"] == "その他"] = 4
df["occupation"][df["occupation"] == "法人・団体、被害者なし"] = 5
# int型に型変換
df["occupation"] = df["occupation"].astype(int)
# 数値化を確認
df.head()

カテゴリ値の確認 ['中学生' '高校生' 'その他' '大学生' '法人・団体、被害者なし' '小学生']

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   occurDate occurTime   age  occupation  isRock
0  2018/7/26        13  10歳代           1       1
1  2018/9/13         6  10歳代           2       1
2  2018/10/6        12  10歳代           2       1
3  2018/12/8        13  10歳代           2       1
4  2018/6/22         7  10歳代           2       1

In [5]:
# age(年齢)の数値化
print("カテゴリ値の確認", df["age"].unique())
df["age"][df["age"] == "10歳未満"] = 10
df["age"][df["age"] == "10歳代"] = 10
df["age"][df["age"] == "20歳代"] = 20
df["age"][df["age"] == "30歳代"] = 30
df["age"][df["age"] == "40歳代"] = 40
df["age"][df["age"] == "50歳代"] = 50
df["age"][df["age"] == "60-64歳"] = 60
df["age"][df["age"] == "65-69歳"] = 60
df["age"][df["age"] == "70歳以上"] = 70
# 以下の理由から、age = 法人・団体、被害者なし の行を削除
# ・年齢の値としてふさわしくない
# ・1496件中7件しか存在しない
df = df[df["age"] != "法人・団体、被害者なし"]
# int型に型変換
df["age"] = df["age"].astype(int)
# 数値化されている事を確認
df.head()

カテゴリ値の確認 ['10歳代' '20歳代' '40歳代' '60-64歳' '30歳代' '50歳代' '70歳以上' '法人・団体、被害者なし'
 '65-69歳' '10歳未満']

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

   occurDate occurTime  age  occupation  isRock
0  2018/7/26        13   10           1       1
1  2018/9/13         6   10           2       1
2  2018/10/6        12   10           2       1
3  2018/12/8        13   10           2       1
4  2018/6/22         7   10           2       1

In [6]:
# occurTime(発生時刻)の数値化
print("カテゴリ値の確認", df["occurTime"].unique())
# "不明"なデータは削除
df = df[df["occurTime"] != "不明"]
# int型に型変換
df['occurTime'] = df['occurTime'].astype(int)
# 数値化を確認
df.head()

カテゴリ値の確認 ['13' '6' '12' '7' '10' '8' '11' '20' '18' '15' '22' '19' '17' '0' '16'
 '14' '9' '21' '23' '不明' '5' '1' '2' '3' '4']

   occurDate  occurTime  age  occupation  isRock
0  2018/7/26         13   10           1       1
1  2018/9/13          6   10           2       1
2  2018/10/6         12   10           2       1
3  2018/12/8         13   10           2       1
4  2018/6/22          7   10           2       1

In [7]:
# occurDate(発生年月日)の数値化
print("カテゴリ値の確認", df["occurDate"].unique())
# occurDateから occurMonth(発生月) を生成する
df['occurMonth'] =  list(map(lambda x: x[1] , df['occurDate'].str.split('/')))
# int型に型変換
df['occurMonth'] = df['occurMonth'].astype(int)
# occurDateの削除
del df['occurDate']
# 数値化されている事を確認
df.head()

カテゴリ値の確認 ['2018/7/26' '2018/9/13' '2018/10/6' '2018/12/8' '2018/6/22' '2018/8/19'
 '2018/7/17' '2018/5/25' '2018/11/9' '2018/6/3' '2018/8/3' '2018/8/4'
 '2018/7/15' '2018/5/29' '2018/12/19' '2018/4/19' '2018/9/16' '2018/2/22'
 '2018/2/27' '2018/9/23' '2018/3/19' '2018/4/7' '2018/5/15' '2018/7/23'
 '2018/5/4' '2017/12/29' '2018/1/4' '2018/8/14' '2018/8/16' '2018/10/10'
 '2018/2/20' '2018/6/4' '2018/7/18' '2018/11/7' '2018/1/11' '2018/1/18'
 '2018/2/26' '2018/3/4' '2018/3/11' '2018/4/13' '2018/8/21' '2018/9/3'
 '2018/11/22' '2018/12/11' '2018/12/25' '2018/6/16' '2017/10/1'
 '2018/7/31' '2018/9/11' '2017/12/22' '2018/4/27' '2018/7/3' '2018/12/6'
 '2018/5/19' '2018/11/16' '2018/3/20' '2018/3/1' '2018/9/6' '2018/6/19'
 '2018/1/8' '2018/9/12' '2016/7/1' '2018/5/31' '2018/4/3' '2018/5/18'
 '2018/10/15' '2018/6/9' '2018/4/30' '2018/9/10' '2018/11/28' '2018/1/20'
 '2018/10/3' '2018/8/18' '2018/6/25' '2018/7/10' '2018/8/30' '2018/6/6'
 '2018/1/29' '2018/4/5' '2018/7/9' '2018/5/5' '2018/6/1' '2018/6/27'
 '2018/10/11' '2018/11/21' '2018/5/10' '2018/3/9' '2018/3/16' '2018/9/9'
 '2018/9/22' '2018/4/26' '2018/8/31' '2018/11/4' '2018/8/28' '2018/11/15'
 '2018/11/20' '2018/3/30' '2018/9/27' '2018/6/2' '2018/8/20' '2018/1/24'
 '2018/9/1' '2018/8/29' '2018/5/1' '2018/5/20' '2018/9/5' '2018/12/1'
 '2018/2/25' '2018/9/19' '2018/10/28' '2018/3/13' '2018/10/9' '2018/6/8'
 '2018/6/13' '2018/6/17' '2018/6/30' '2018/8/11' '2018/9/20' '2018/7/27'
 '2018/7/30' '2018/2/16' '2018/11/25' '2018/6/15' '2018/9/14' '2018/3/12'
 '2018/4/20' '2018/6/29' '2018/4/17' '2018/7/22' '2018/6/23' '2018/10/17'
 '2018/8/15' '2018/9/7' '2018/9/28' '2018/1/25' '2018/4/11' '2018/7/16'
 '2018/5/11' '2018/3/27' '2018/1/27' '2018/7/21' '2018/10/23' '2017/5/24'
 '2018/1/19' '2018/2/9' '2018/9/21' '2018/12/3' '2018/5/22' '2017/9/20'
 '2018/5/26' '2018/7/8' '2018/8/26' '2018/8/2' '2018/8/23' '2018/8/5'
 '2018/1/9' '2018/10/1' '2018/1/22' '2018/8/7' '2018/8/9' '2018/7/7'
 '2018/3/14' '2018/9/29' '2018/4/10' '2018/5/2' '2018/12/24' '2018/1/23'
 '2018/12/7' '2018/12/10' '2017/8/24' '2018/10/8' '2018/11/10' '2018/5/9'
 '2018/7/25' '2018/11/3' '2018/11/29' '2018/11/13' '2018/1/12' '2018/2/10'
 '2018/8/17' '2018/10/21' '2018/1/1' '2018/7/5' '2017/11/17' '2018/9/26'
 '2018/8/12' '2018/2/15' '2018/3/31' '2018/4/24' '2018/5/17' '2018/9/17'
 '2018/3/17' '2018/12/18' '2018/2/12' '2018/4/29' '2018/5/12' '2018/10/5'
 '2018/11/11' '2018/5/27' '2018/7/20' '2018/9/15' '2018/12/13'
 '2018/12/21' '2018/12/2' '2018/11/27' '2018/11/18' '2018/1/17'
 '2018/12/20' '2018/3/15' '2018/2/24' '2018/8/13' '2018/7/1' '2017/9/1'
 '2018/3/26' '2018/4/23' '2018/3/18' '2018/4/21' '2018/5/28' '2018/7/29'
 '2018/11/19' '2018/2/19' '2018/2/28' '2018/6/11' '2018/9/24' '2017/12/28'
 '2017/12/25' '2018/7/4' '2018/10/4' '2018/11/5' '2018/4/2' '2018/2/7'
 '2018/1/15' '2018/2/17' '2018/10/12' '2018/10/13' '2018/2/8' '2018/3/6'
 '2018/8/1' '2018/2/21' '2018/5/24' '2018/6/24' '2018/6/20' '2018/12/15'
 '2018/7/2' '2018/3/28' '2018/5/6' '2018/4/6' '2017/11/10' '2018/11/14'
 '2018/5/23' '2018/10/26' '2017/12/30' '2018/1/10' '2018/6/7' '2018/6/14'
 '2018/8/8' '2018/12/17' '2018/1/31' '2018/6/26' '2018/9/30' '2018/6/28'
 '2018/11/17' '2018/11/30' '2018/4/4' '2018/7/12' '2018/10/18'
 '2017/12/31' '2018/6/21' '2018/7/13' '2018/8/10' '2018/10/2' '2018/3/29'
 '2018/4/15' '2018/4/14' '2018/11/26' '2018/12/5' '2018/1/5' '2018/2/18'
 '2018/5/30' '2018/8/6' '2018/12/4' '2018/7/24' '2018/9/2' '2018/3/7'
 '2018/4/28' '2018/11/8' '2018/5/3' '2018/10/24' '2018/9/8' '2018/8/25'
 '2018/4/16' '2018/5/21' '2018/3/3' '2017/12/26' '2018/3/23' '2018/7/19'
 '2018/10/19' '2018/11/2' '2018/12/14' '2018/6/10' '2018/10/7' '2018/1/13'
 '2018/8/24' '2018/7/11' '2018/12/26' '2018/4/12' '2018/10/25'
 '2018/12/16' '2018/5/14' '2018/12/27' '2018/2/5' '2018/10/20' '2018/3/24'
 '2017/9/22' '2018/2/13' '2018/5/16' '2018/8/22' '2018/10/16' '2018/11/23'
 '2018/1/30' '2018/1/14' '2018/5/8' '2018/12/23' '2018/12/9' '2018/1/16'
 '2018/4/25' '2018/7/14' '2018/5/13' '2018/2/6' '2018/4/1' '2018/7/6'
 '2016/12/25' '2017/11/5' '2018/8/27' '2018/1/7' '2018/11/12' '2018/4/22'
 '2018/2/14' '2018/10/29' '2018/6/5' '2018/10/22' '2018/10/31' '2018/9/18'
 '2018/2/1' '2018/2/3' '2018/12/30' '2018/11/24' '2018/1/28' '2018/6/12'
 '2018/6/18' '2018/3/22' '2018/1/26' '2017/10/10' '2017/11/2' '2018/10/27'
 '2018/11/1' '2018/11/6' '2018/10/30' '2018/5/7' '2018/7/28' '2017/12/2'
 '2018/12/22' '2018/4/9' '2018/2/4' '2018/9/4' '2018/10/14' '2018/1/6'
 '2017/12/27' '2018/9/25' '2014/5/1']

   occurTime  age  occupation  isRock  occurMonth
0         13   10           1       1           7
1          6   10           2       1           9
2         12   10           2       1          10
3         13   10           2       1          12
4          7   10           2       1           6

In [8]:
# 型も数値型であることを確認
print(df.dtypes)
# 数値化したデータをcsv出力
df.to_csv('./CSV/output/transform_bohan_data.csv')

occurTime     int64
age           int64
occupation    int64
isRock        int64
occurMonth    int64
dtype: object